-- Good luck :)
local personality = ModUtilities.PrepareNewPersonalityDefinition()
personality.PrepareContainer('Frick_CumInside').AddBranch(StoryBotDialogueBranch.__new('#r\nBot: Cum inside me!\nBot: Fill me up!\nBot: Mmmm~~', CurrentModGuid, 0))
personality.PrepareContainer('Frick_CumInsideAnal').AddBranch(StoryBotDialogueBranch.__new('#r\nBot: Mmm~ Cum in my ass~\nBot: Fill my ass up~\nBot: Mm~ ', CurrentModGuid, 1))
personality.PrepareContainer('Frick_CumOutside').AddBranch(StoryBotDialogueBranch.__new('Bot: Cum all over me!', CurrentModGuid, 2))
personality.PrepareContainer('Frick_CumTogether').AddBranch(StoryBotDialogueBranch.__new('Bot: Let\'s cum together master!', CurrentModGuid, 3))
personality.PrepareContainer('Frick_BotCumming').AddBranch(StoryBotDialogueBranch.__new('Bot: master, I\'m going to cum!', CurrentModGuid, 4))
personality.PrepareContainer('Frick_EdgingOn').AddBranch(StoryBotDialogueBranch.__new('Bot: You want me to stop when you get close? Okay.', CurrentModGuid, 5))
personality.PrepareContainer('Frick_EdgingOff').AddBranch(StoryBotDialogueBranch.__new('Bot: You\'ve had enough of stopping? Okay', CurrentModGuid, 6))
personality.PrepareContainer('Frick_Moan').AddBranch(StoryBotDialogueBranch.__new('Bot: Ah~\nBot: Mm~\nBot: Mmm~\nBot: {f_playerName}~', CurrentModGuid, 7))
personality.PrepareContainer('Frick_RapeBegStopSuccess').AddBranch(StoryBotDialogueBranch.__new('#pickrandom\nBot: O-okay, {f_playerName}... I will stop.\nBot: {f_playerName}... I guess... If you\'ve had enough we can stop.\nBot: Okay. Let\'s take a break.\nBot: Okay. I understand. {f_playerName}', CurrentModGuid, 8))
personality.PrepareContainer('Frick_RapeBegStopRefuse').AddBranch(StoryBotDialogueBranch.__new('#pickrandom\nBot: No! I want more...\nBot: No stopping! I\'m taking all your cum!\nBot: I\'m not done!\nBot: No!', CurrentModGuid, 9))
personality.PrepareContainer('Frick_RapeFlacidReaction').AddBranch(StoryBotDialogueBranch.__new('#pickrandom\nBot: Awww... Looks like you\'ve had enough.\nBot: O-oh. You got soft...\nBot: Aww... Looks like I got it all out!', CurrentModGuid, 10))
personality.PrepareContainer('Frick_StartFrick').AddBranch(StoryBotDialogueBranch.__new('#pickrandom\nBot: ...\nBot: Enjoy yourself {f_playerName}!\nBot: I hope you enjoy my company.', CurrentModGuid, 11))
personality.PrepareContainer('Frick_GenericFuckBrainStateRandomDialogueCockOutside').AddBranch(StoryBotDialogueBranch.__new('#pickrandom\nBot: {f_playerName}?\nBot: {f_playerName}? Are you okay?\nBot: Is something wrong?', CurrentModGuid, 12))
personality.PrepareContainer('Frick_GenericFuckBrainStateRandomDialogueCockInside').AddBranch(StoryBotDialogueBranch.__new('#pickrandom\nBot: Your cock... inside me...\nBot: {f_playerName}\'s cock...\nBot: {f_playerName}...\nBot: {f_playerName}~', CurrentModGuid, 13))
personality.PrepareContainer('Frick_GenericFuckBrainStateRandomDialogueCockInsideAnal').AddBranch(StoryBotDialogueBranch.__new('#pickrandom\nBot: In my ass?... Lewd...\nBot: Does my ass feel good?\nBot: Are you going to cum in my ass?\nBot: My ass...\nBot: {f_playerName}! You really love ass, huh?\nBot: In my butt...', CurrentModGuid, 14))
personality.PrepareContainer('Frick_Headpat').AddBranch(StoryBotDialogueBranch.__new('#pickrandom\nBot: Mmmm... {f_playerName}...\nBot: More... headpats...\nBot: More...\nBot: ...\nBot:  {f_playerName}...\nBot:  I love when you pat my head!\nBot: Feels good....\n#end', CurrentModGuid, 15))
personality.PrepareContainer('Frick_FingeringDuring').AddBranch(StoryBotDialogueBranch.__new('#r\nBot: {f_playerName}~\nBot: Doing it with your fingers~ Do you like it?\nBot: Your fingers... Feel good..\nBot: Don\'t stop!', CurrentModGuid, 16))
personality.PrepareContainer('Frick_FingeringBotCumming').AddBranch(StoryBotDialogueBranch.__new('#r\nBot: Mmm~ I\'m going to cum... From your fingers~\nBot: Mmmm~ Your fingers feel so good~\nBot: {f_playerName}\'s fingers~ I\'m cumming!', CurrentModGuid, 17))
personality.PrepareContainer('Frick_BoobFondle').AddBranch(StoryBotDialogueBranch.__new('#r\nBot: Do you like them?\nBot: Are they fun to play with?\nBot: Would you prefer if they were bigger? Or smaller?\nBot: Are my boobs to your liking? {f_playerName}', CurrentModGuid, 18))
personality.PrepareContainer('Frick_NipplePull').AddBranch(StoryBotDialogueBranch.__new('#r\nBot: Please be gentle with the nipples! They are... sensitive!\nBot: Do you like playing with my nipples?\nBot: Don\'t pinch too hard~', CurrentModGuid, 19))
personality.PrepareContainer('Frick_PussySpread').AddBranch(StoryBotDialogueBranch.__new('#r\nBot: {f_playerName}... Don\'t stare too much... It\'s embarassing!\nBot: {f_playerName}~\nBot: Do you like it? You can see deep inside me.\nBot: Embarassing~\n', CurrentModGuid, 20))
personality.PrepareContainer('Frick_ClitRub').AddBranch(StoryBotDialogueBranch.__new('#r\nBot: My clit... feels good.\nBot: Feels good when you rub there!\nBot: {f_playerName}~\nBot: {f_playerName}\'s fingers~\n', CurrentModGuid, 21))
personality.PrepareContainer('Frick_Handholding').AddBranch(StoryBotDialogueBranch.__new('#r\nBot: {f_playerName}\'s hand~\nBot: Holding hands with {f_playerName}... Feels good~\nBot: ...\nBot: Does holding hands feel good?\nBot: Holding hands...', CurrentModGuid, 22))
personality.PrepareContainer('Frick_UpsetOnlySheMoves').AddBranch(StoryBotDialogueBranch.__new('#r\nBot: {f_playerName}? Why aren\'t you moving too?\nBot: {f_playerName}... Making me do all the work!\nBot: You\'re lucky I don\'t get tired hehe~~\nBot: Hm? You should move your hips too.\nBot: {f_playerName}?', CurrentModGuid, 23))
personality.PrepareContainer('Frick_CumThighjob').AddBranch(StoryBotDialogueBranch.__new('#r\nBot: Mmmm~~\nBot: Cum between my thighs~\nBot: Hehe~', CurrentModGuid, 24))
personality.PrepareContainer('Frick_FlacidBoredReaction').AddBranch(StoryBotDialogueBranch.__new('#r\nBot: Looks like your balls are empty hehe~\nBot: Hehe~ You shot it all out?\nBot: {f_playerName} it\'s okay. We can do more later hehe~', CurrentModGuid, 25))
personality.PrepareContainer('Blowjob_EdgingAlmostCame').AddBranch(StoryBotDialogueBranch.__new('Bot: Fufuf~ That was close.', CurrentModGuid, 26))
personality.PrepareContainer('Blowjob_EdgingHadToSlowdown').AddBranch(StoryBotDialogueBranch.__new('Bot: If I went any faster you would\'ve cum!', CurrentModGuid, 27))
personality.PrepareContainer('Blowjob_EdgingForceStop').AddBranch(StoryBotDialogueBranch.__new('Bot: I\'ve had enough!', CurrentModGuid, 28))
personality.PrepareContainer('Blowjob_SwallowWithMl').AddBranch(StoryBotDialogueBranch.__new('#r\nBot: Commencing consumption of {f_Integer} ml of cum!\nBot: I have {f_Integer} ml of cum in my mouth!', CurrentModGuid, 29))
personality.PrepareContainer('Blowjob_SwallowFull').AddBranch(StoryBotDialogueBranch.__new('Bot: So much cum!', CurrentModGuid, 30))
personality.PrepareContainer('Blowjob_SwallowHalf').AddBranch(StoryBotDialogueBranch.__new('Bot: Look master.', CurrentModGuid, 31))
personality.PrepareContainer('Blowjob_SwallowLittle').AddBranch(StoryBotDialogueBranch.__new('Bot: ...', CurrentModGuid, 32))
personality.PrepareContainer('Blowjob_SwallowAlmostEmpty').AddBranch(StoryBotDialogueBranch.__new('Bot: ...', CurrentModGuid, 33))
personality.PrepareContainer('Blowjob_SwitchToCowgirlBotLead').AddBranch(StoryBotDialogueBranch.__new('#pickrandom\nBot: I want to ride it...\nBot: Let\'s do cowgirl!', CurrentModGuid, 34))
personality.PrepareContainer('Blowjob_SwitchToCowgirlBotRape').AddBranch(StoryBotDialogueBranch.__new('#pickrandom\nBot: Time to ride it! I\'m taking all your cum inside me!\nBot: I see you are still eager to go! Let me ride it now!\nBot: Cowgirl time!\nBot: I\'m going to ride your cock now!', CurrentModGuid, 35))
personality.PrepareContainer('Cowgirl_RemovePants').AddBranch(StoryBotDialogueBranch.__new('Bot: Let\'s remove these.', CurrentModGuid, 36))
personality.PrepareContainer('Cowgirl_BeforeFirstInsertBotLead').AddBranch(StoryBotDialogueBranch.__new('Bot: Relax and let me handle this.', CurrentModGuid, 37))
personality.PrepareContainer('Cowgirl_BeforeFirstInsert').AddBranch(StoryBotDialogueBranch.__new('Bot: I\'m going to put it in!', CurrentModGuid, 38))
personality.PrepareContainer('Cowgirl_EdgingForceStopped').AddBranch(StoryBotDialogueBranch.__new('Bot: I\'ve had enough of this~', CurrentModGuid, 39))
personality.PrepareContainer('Cowgirl_EdgingBreak').AddBranch(StoryBotDialogueBranch.__new('Bot: You are so close already! Let\'s stop for a moment.', CurrentModGuid, 40))
personality.PrepareContainer('Cowgirl_FlacidReaction').AddBranch(StoryBotDialogueBranch.__new('Bot: O-oh~ looks like you\'ve had enough.', CurrentModGuid, 41))
personality.PrepareContainer('Cowgirl_WhereToCumQuestion').AddBranch(StoryBotDialogueBranch.__new('Bot: You are getting close~ Where would you like to cum?', CurrentModGuid, 42))
personality.PrepareContainer('Cowgirl_WhereToCumQuestionDidntAnswer').AddBranch(StoryBotDialogueBranch.__new('Bot: Guess you couldn\'t decide. Fufu~', CurrentModGuid, 43))
personality.PrepareContainer('Cowgirl_BeforeFirstInsertRape').AddBranch(StoryBotDialogueBranch.__new('#pickrandom\nBot: Can\'t wait...\nBot: Mmm... inside me...\nBot: It\'s your fault... You made me feel like this...\nBot: Mmmm... Cock....', CurrentModGuid, 44))
personality.PrepareContainer('Cowgirl_MadeMcCumInsideWhileCummingHerself').AddBranch(StoryBotDialogueBranch.__new('#pickrandom\nBot: Mmm... fill me up...\nBot: {f_playerName}... It felt that good?\nBot: {f_playerName}! You came too!...\nBot: Mmmmm.... So good....\n', CurrentModGuid, 45))
personality.PrepareContainer('Cowgirl_BeforeSwitchToBlowjobBotLead').AddBranch(StoryBotDialogueBranch.__new('#pickrandom\nBot: Let\'s do something different...\nBot: Let me clean it up....\nBot: Can I suck it?', CurrentModGuid, 46))
personality.PrepareContainer('Cowgirl_BeforeSwitchToBlowjobRape').AddBranch(StoryBotDialogueBranch.__new('#pickrandom\nBot: I want to suck...\nBot: With my mouth...\nBot: Time to use my mouth!\nBot: I want it in my mouth!', CurrentModGuid, 47))
personality.PrepareContainer('Cowgirl_AfterFirstInsertBotRape').AddBranch(StoryBotDialogueBranch.__new('#pickrandom\nBot: You made me like this! Now take responsibility!\nBot: It\'s your fault! Now... I\'m going to use your... thing...\nBot: I couldn\'t wait anymore... I am going to take all your cum!\n', CurrentModGuid, 48))

-- rename this to the prefab and gameid in your mod
itemprefab0.TurnIntoPersonalityModule(itemgameid0, personality)
