from __future__ import annotations

import argparse
import json
import re
from collections import Counter, defaultdict
from dataclasses import dataclass
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
LIBRARY = ROOT / "library"
LUAS = ROOT / "luas"
REALMOD_SCRIPT = ROOT / "mod" / "realmod" / "script.lua"
DEBUG_MOD_SCRIPT = ROOT / "examples" / "callback_debug_mod_real" / "script.lua"
ANALYSIS = ROOT / "analysis"
RUNTIME_CALLBACK_EVIDENCE = ROOT / "data" / "runtime_callback_evidence.json"
PROVENANCE = """<!--
Generated by: tools/catalog_lua_callbacks.py
Inputs:
- library/*.d.lua
- luas/*.lua
- mod/realmod/script.lua
- examples/callback_debug_mod_real/script.lua
Regenerate:
python tools/catalog_lua_callbacks.py
Do not edit manually unless explicitly noted.
-->

"""


@dataclass
class CallbackEntry:
    source: str
    line: int
    owner: str
    kind: str
    name: str
    signature: str
    domain: str
    risk: str


CALLBACK_FIELD_RE = re.compile(r"^---@field\s+([A-Za-z_][A-Za-z0-9_]*)\s+(.*fun\(.+)$")
CALLBACK_PARAM_RE = re.compile(r"^---@param\s+([A-Za-z_][A-Za-z0-9_]*)\s+(.*fun\(.+)$")
CALLBACK_RETURN_RE = re.compile(r"^---@return\s+(.*fun\(.+)$")
OVERLOAD_RE = re.compile(r"^---@overload\s+fun\((.*fun\(.+)\)")
CLASS_RE = re.compile(r"^---@class\s+([A-Za-z_][A-Za-z0-9_]*)")
FUNCTION_RE = re.compile(r"^function\s+([A-Za-z_][A-Za-z0-9_:.]*)\(")
LUA_STRING_FIELD_RE = re.compile(r"([A-Za-z_][A-Za-z0-9_]*)\s*=\s*([\"'])(.*?)\2", re.S)
LUA_BOOL_FIELD_RE = re.compile(r"([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(true|false)\b")

CRITICAL_CALLBACK_KEYS = [
    "ItemPrefab.OnUse",
    "ItemPrefab.OnUnpack",
    "ItemPrefab.SpecialEffectAction",
    "ItemPrefab.SetRandomItemPostProcessing",
    "EdibleItemPrefabData.CreateInstance",
    "EdibleItemPrefabData.CreateInstanceDish",
    "ModUtilities.AddSingleBuyItemToShop.availabilityFunc",
    "ModUtilities.AddGenericItemToShop.availabilityFunc",
    "ItemScopeConditionCustom.CreateInstance",
    "TextureOverriderManager.GetSpecialEffectsAction",
    "ItemPrefab.SetCustomShader",
    "StoryCondition.Delegate",
    "StoryCondition.Lua",
    "ModUtilities.StartCoroutine",
    "UiOverlay.*",
    "ItemManager.*events",
]

EXPECTED_ITEM_CATEGORIES = [
    "Clothing",
    "Food",
    "FoodCookedDish",
    "Usable",
    "Package",
    "Room",
    "Modules",
    "Fish",
    "CookingIngredient",
    "FishingTrash",
    "Meds",
    "Soap",
    "AnonEquip",
    "Other",
]


def domain_for(owner: str, source: str) -> str:
    text = f"{source} {owner}".lower()
    if "item" in text or "shop" in text or "edible" in text or "fish" in text:
        return "items/food/shop"
    if "story" in text or "flowchart" in text or "condition" in text:
        return "story/fungus"
    if "ui" in text or "popup" in text or "browser" in text:
        return "ui"
    if "texture" in text or "part" in text or "unity" in text:
        return "unity/texture"
    if "coroutine" in text or "managedcoroutine" in text:
        return "coroutine"
    return "general"


def risk_for(owner: str, name: str, signature: str) -> str:
    text = f"{owner}.{name} {signature}".lower()
    if any(word in text for word in ["save", "delete", "reset", "force", "money", "inventory"]):
        return "state/save-sensitive"
    if any(word in text for word in ["open", "popup", "browser", "equip", "unequip", "shop", "buy"]):
        return "ui/runtime-sensitive"
    if any(word in text for word in ["item", "nutrition", "edible", "specialeffect", "onuse", "onunpack"]):
        return "runtime-callback"
    if any(word in text for word in ["story", "flowchart", "condition", "activate"]):
        return "story-context"
    return "unknown"


def parse_stub_callbacks() -> list[CallbackEntry]:
    entries: list[CallbackEntry] = []
    for path in sorted(LIBRARY.glob("*.d.lua")):
        current_class = ""
        pending: list[tuple[int, str, str, str]] = []
        lines = path.read_text(encoding="utf-8").splitlines()
        for line_no, line in enumerate(lines, start=1):
            class_match = CLASS_RE.match(line)
            if class_match:
                current_class = class_match.group(1)

            field_match = CALLBACK_FIELD_RE.match(line)
            if field_match:
                owner = current_class or "<global>"
                name = field_match.group(1)
                signature = field_match.group(2).strip()
                entries.append(
                    CallbackEntry(
                        path.relative_to(ROOT).as_posix(),
                        line_no,
                        owner,
                        "field",
                        name,
                        signature,
                        domain_for(owner, path.name),
                        risk_for(owner, name, signature),
                    )
                )
                continue

            param_match = CALLBACK_PARAM_RE.match(line)
            if param_match:
                pending.append((line_no, "param", param_match.group(1), param_match.group(2).strip()))
                continue

            return_match = CALLBACK_RETURN_RE.match(line)
            if return_match:
                pending.append((line_no, "return", "return", return_match.group(1).strip()))
                continue

            overload_match = OVERLOAD_RE.match(line)
            if overload_match:
                pending.append((line_no, "overload", "overload", overload_match.group(1).strip()))
                continue

            function_match = FUNCTION_RE.match(line)
            if function_match:
                owner = function_match.group(1)
                for pending_line, kind, name, signature in pending:
                    entries.append(
                        CallbackEntry(
                            path.relative_to(ROOT).as_posix(),
                            pending_line,
                            owner,
                            kind,
                            name,
                            signature,
                            domain_for(owner, path.name),
                            risk_for(owner, name, signature),
                        )
                    )
                pending = []
            elif line.strip() == "":
                pending = pending[-8:]
    return entries


def read_text(path: Path) -> str:
    if not path.exists():
        return ""
    return path.read_text(encoding="utf-8", errors="replace")


def lua_sources() -> list[Path]:
    sources = []
    if LUAS.exists():
        sources.extend(sorted(LUAS.glob("*.lua")))
    if REALMOD_SCRIPT.exists():
        sources.append(REALMOD_SCRIPT)
    return sources


def source_label(path: Path) -> str:
    return path.relative_to(ROOT).as_posix()


def analyze_lua_usage() -> dict[str, Counter[str]]:
    patterns = {
        "field_callbacks": re.compile(
            r"\.([A-Za-z_][A-Za-z0-9_]*(?:OnUse|OnUnpack|SpecialEffectAction|RandomItemPostProcessing|Action|Callback|Func))\s*="
        ),
        "edible_create": re.compile(r"EdibleItemPrefabData\.CreateInstance(?:Dish)?\s*\("),
        "story_activate": re.compile(r"SetOnActivateAction\s*\("),
        "start_coroutine": re.compile(r"StartCoroutine\s*\("),
        "function_defs": re.compile(r"\bfunction\s*(?:[A-Za-z_][A-Za-z0-9_:.]*)?\s*\("),
        "inline_functions": re.compile(r"=\s*function\s*\("),
    }
    result: dict[str, Counter[str]] = {name: Counter() for name in patterns}
    for path in lua_sources():
        text = read_text(path)
        label = source_label(path)
        for name, regex in patterns.items():
            matches = regex.findall(text)
            if name == "field_callbacks":
                for match in matches:
                    result[name][f"{label}:{match}"] += 1
            else:
                result[name][label] = len(matches)
    return result


def extract_lua_table_block(text: str, local_name: str) -> str:
    match = re.search(rf"\blocal\s+{re.escape(local_name)}\s*=\s*\{{", text)
    if not match:
        return ""
    start = text.find("{", match.start())
    depth = 0
    in_string: str | None = None
    escaped = False
    for index in range(start, len(text)):
        char = text[index]
        if in_string:
            if escaped:
                escaped = False
            elif char == "\\":
                escaped = True
            elif char == in_string:
                in_string = None
            continue
        if char in {"'", '"'}:
            in_string = char
            continue
        if char == "{":
            depth += 1
        elif char == "}":
            depth -= 1
            if depth == 0:
                return text[start + 1:index]
    return text[start + 1:]


def split_top_level_table_entries(block: str) -> list[str]:
    entries: list[str] = []
    current: list[str] = []
    depth = 0
    in_string: str | None = None
    escaped = False
    entry_start_depth = 0
    for char in block:
        if in_string:
            current.append(char)
            if escaped:
                escaped = False
            elif char == "\\":
                escaped = True
            elif char == in_string:
                in_string = None
            continue
        if char in {"'", '"'}:
            in_string = char
            current.append(char)
            continue
        if char == "{":
            if depth == 0:
                current = []
                entry_start_depth = 1
            else:
                current.append(char)
            depth += 1
            continue
        if char == "}":
            depth -= 1
            if depth == 0 and entry_start_depth:
                entries.append("".join(current))
                current = []
                entry_start_depth = 0
            else:
                current.append(char)
            continue
        if depth > 0:
            current.append(char)
    return entries


def parse_lua_key_values(entry: str) -> dict[str, str]:
    fields: dict[str, str] = {}
    for match in LUA_STRING_FIELD_RE.finditer(entry):
        fields[match.group(1)] = match.group(3)
    for match in LUA_BOOL_FIELD_RE.finditer(entry):
        fields.setdefault(match.group(1), match.group(2))
    return fields


def parse_debug_mod_matrix() -> tuple[list[dict[str, str]], list[dict[str, str]]]:
    text = read_text(DEBUG_MOD_SCRIPT)
    coverage: list[dict[str, str]] = []
    categories: list[dict[str, str]] = []
    for table_name, target in [
        ("DEBUG_CALLBACK_COVERAGE", coverage),
        ("DEBUG_ITEM_CATEGORIES", categories),
    ]:
        block = extract_lua_table_block(text, table_name)
        for entry in split_top_level_table_entries(block):
            fields = parse_lua_key_values(entry)
            if table_name == "DEBUG_CALLBACK_COVERAGE" and {"callback_key", "case_id", "status"} <= fields.keys():
                target.append(fields)
            elif table_name == "DEBUG_ITEM_CATEGORIES" and {"category_name", "id"} <= fields.keys():
                target.append(fields)
    return coverage, categories


def load_runtime_evidence(path: Path = RUNTIME_CALLBACK_EVIDENCE) -> dict:
    if not path.exists():
        return {}
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        return {}


def evidence_callbacks(evidence: dict) -> dict[str, dict]:
    callbacks = evidence.get("callbacks", {})
    return callbacks if isinstance(callbacks, dict) else {}


def evidence_for_key(evidence: dict, key: str) -> dict:
    return evidence_callbacks(evidence).get(key, {})


def evidence_key_for_entry(entry: CallbackEntry) -> str:
    return f"{entry.owner}.{entry.name}"


def runtime_status_text(evidence: dict, key: str) -> str:
    item = evidence_for_key(evidence, key)
    if not item:
        return ""
    status = item.get("status", "")
    count = item.get("observed_count", 0)
    if count:
        return f"{status} ({count})"
    return str(status)


def runtime_status_counts(evidence: dict) -> Counter[str]:
    counter: Counter[str] = Counter()
    for item in evidence_callbacks(evidence).values():
        if isinstance(item, dict):
            counter[str(item.get("status") or "unknown")] += 1
    return counter


def render_contexts(entries: list[CallbackEntry], usage: dict[str, Counter[str]], evidence: dict) -> str:
    by_domain = Counter(entry.domain for entry in entries)
    by_risk = Counter(entry.risk for entry in entries)
    lines = [
        "# Lua callback contexts",
        "",
        "Generated from LuaCATS stubs plus local Lua usage evidence. This report does not add APIs automatically.",
        "",
        "## Summary",
        "",
        f"- Stub callback entries: {len(entries)}",
        f"- Lua sources scanned: {len(lua_sources())}",
        "",
        "Domains:",
        *[f"- `{key}`: {value}" for key, value in by_domain.most_common()],
        "",
        "Risk buckets:",
        *[f"- `{key}`: {value}" for key, value in by_risk.most_common()],
        "",
        "## Stub callback catalog",
        "",
        "| Source | Line | Owner | Kind | Name | Signature | Domain | Risk | Runtime evidence |",
        "|---|---:|---|---|---|---|---|---|---|",
    ]
    for entry in entries:
        runtime = runtime_status_text(evidence, evidence_key_for_entry(entry)) or "-"
        lines.append(
            f"| `{entry.source}` | {entry.line} | `{entry.owner}` | `{entry.kind}` | `{entry.name}` | `{entry.signature}` | `{entry.domain}` | `{entry.risk}` | `{runtime}` |"
        )

    lines.extend(["", "## Runtime callback evidence", ""])
    status_counts = runtime_status_counts(evidence)
    if status_counts:
        for status, count in status_counts.most_common():
            lines.append(f"- `{status}`: {count}")
    else:
        lines.append("- No `data/runtime_callback_evidence.json` entries found.")

    lines.extend(["", "## Lua usage evidence", ""])
    for name, counter in usage.items():
        lines.extend([f"### {name}", ""])
        if not counter:
            lines.append("- None")
        else:
            for key, count in counter.most_common(80):
                lines.append(f"- `{key}`: {count}")
        lines.append("")
    return "\n".join(lines) + "\n"


def render_debug_cases(entries: list[CallbackEntry], usage: dict[str, Counter[str]], evidence: dict) -> str:
    indexed = defaultdict(list)
    for entry in entries:
        indexed[entry.domain].append(entry)

    lines = [
        "# Callback debug cases",
        "",
        "Recommended callback probe targets. All cases require manual opt-in and should be wrapped, not invoked manually.",
        "",
        "## High priority cases",
        "",
        "### Runtime evidence status",
        "",
    ]
    status_counts = runtime_status_counts(evidence)
    if status_counts:
        lines.extend(f"- `{status}`: {count}" for status, count in status_counts.most_common())
    else:
        lines.append("- No runtime callback evidence JSON found yet.")
    lines.extend(
        [
            "",
        "### Food nutrition filler",
        "",
        "- API: `EdibleItemPrefabData.CreateInstance(edibleTypeEnum, getNutritionProfile)`",
        "- Expected callback shape: `fun(item: Item, nutritionProfile: EdibleItemNutritionProfile)`",
        "- Real usage evidence: `luas/foods.lua` and `mod/realmod/script.lua` use nutrition filler callbacks.",
        "",
        "### Item use/unpack/effect",
        "",
        "- APIs/fields: `ItemPrefab.OnUse`, `ItemPrefab.OnUnpack`, `ItemPrefab.SpecialEffectAction`",
        "- Context: runtime item invocation; arguments should be probed at callback time.",
        "",
        "### Story/UI/coroutine",
        "",
        "- APIs include `SetOnActivateAction`, `Activate(onFinished)`, popup callbacks and `StartCoroutine`.",
        "- Context may depend on save, scene and Fungus state.",
        "",
        "## Evidence by domain",
        "",
        ]
    )
    for domain, domain_entries in sorted(indexed.items()):
        lines.append(f"### {domain}")
        lines.append("")
        for entry in domain_entries[:30]:
            lines.append(f"- `{entry.owner}` `{entry.kind}` `{entry.name}` -> `{entry.signature}`")
        lines.append("")

    field_callbacks = usage.get("field_callbacks", Counter())
    lines.extend(["## Field callback assignments in Lua sources", ""])
    if field_callbacks:
        for key, count in field_callbacks.most_common(100):
            lines.append(f"- `{key}`: {count}")
    else:
        lines.append("- None")
    return "\n".join(lines) + "\n"


def render_coverage(coverage: list[dict[str, str]], categories: list[dict[str, str]], evidence: dict) -> str:
    by_key = {entry.get("callback_key", ""): entry for entry in coverage}
    category_names = {entry.get("category_name", "") for entry in categories}

    lines = [
        "# Callback debug coverage",
        "",
        "Generated from `examples/callback_debug_mod_real/script.lua` and the callback catalog.",
        "The debug mod is opt-in; coverage means a case is registered for manual runtime testing, not executed automatically.",
        "",
        "## Item category matrix",
        "",
        "| ItemCategory | Debug item case | Status |",
        "|---|---|---|",
    ]
    category_by_name = {entry.get("category_name", ""): entry for entry in categories}
    for category in EXPECTED_ITEM_CATEGORIES:
        entry = category_by_name.get(category)
        status = "covered" if category in category_names else "missing"
        lines.append(f"| `{category}` | `{entry.get('id', '') if entry else ''}` | `{status}` |")

    lines.extend(
        [
            "",
            "## Critical callback coverage",
            "",
            "| Callback | Case | Status | Runtime evidence | Trigger | Reason |",
            "|---|---|---|---|---|---|",
        ]
    )
    for key in CRITICAL_CALLBACK_KEYS:
        entry = by_key.get(key)
        runtime = runtime_status_text(evidence, key) or "-"
        if entry:
            lines.append(
                f"| `{key}` | `{entry.get('case_id', '')}` | `{entry.get('status', '')}` | `{runtime}` | `{entry.get('trigger_hint', '')}` | `{entry.get('reason', '')}` |"
            )
        else:
            lines.append(f"| `{key}` |  | `missing` | `{runtime}` |  |  |")

    lines.extend(
        [
            "",
            "## All declared debug cases",
            "",
            "| Line | Callback | Case | Status | Runtime evidence | Risk | Trigger | Reason |",
            "|---:|---|---|---|---|---|---|---|",
        ]
    )
    for entry in coverage:
        runtime = runtime_status_text(evidence, entry.get("callback_key", "")) or "-"
        lines.append(
            f"| {entry.get('line', '')} | `{entry.get('callback_key', '')}` | `{entry.get('case_id', '')}` | `{entry.get('status', '')}` | `{runtime}` | `{entry.get('risk', '')}` | `{entry.get('trigger_hint', '')}` | `{entry.get('reason', '')}` |"
        )
    return "\n".join(lines) + "\n"


def render_manual_steps(coverage: list[dict[str, str]], categories: list[dict[str, str]]) -> str:
    lines = [
        "# Callback debug manual test steps",
        "",
        "Run only in a disposable test save. The debug mod is inert until flags in `script.lua` are enabled manually.",
        "",
        "## Baseline",
        "",
        "1. Set `ENABLE_DEBUG_ITEMS = true`.",
        "2. Set `ENABLE_CALLBACK_PROBE = true`.",
        "3. Keep optional groups disabled unless the specific scenario needs them.",
        "4. Load the mod and check for `callback-report-*.txt` or console chunks.",
        "",
        "## Item category matrix",
        "",
        "Register all category items, then inspect item list/shop availability depending on enabled flags.",
        "",
    ]
    for entry in categories:
        lines.append(f"- `{entry.get('category_name')}`: `{entry.get('id')}`")

    lines.extend(
        [
            "",
            "## Runtime triggers",
            "",
            "- Use a debug item to trigger `ItemPrefab.OnUse`.",
            "- Unpack the package debug item to trigger `ItemPrefab.OnUnpack`.",
            "- Eat food, fish, cooking ingredient or cooked dish debug items to trigger nutrition callbacks.",
            "- Enable `DEBUG_ADD_TO_SHOP = true` and open the configured shop to trigger availability callbacks.",
            "- Equip/render slotted debug items to give item-scope conditions and special effects a chance to run.",
            "- Enable `DEBUG_ENABLE_TEXTURE_CALLBACK_CASES = true` only when validating texture override callbacks.",
            "- Enable `DEBUG_ENABLE_STORY_CONDITION_CASES = true` to create story conditions; do not call `ConditionMet` manually from startup.",
            "- Enable `DEBUG_ENABLE_COROUTINE_CASES = true` only when validating coroutine lifetime.",
            "",
            "## Contextual or intentionally not automated",
            "",
        ]
    )
    for entry in coverage:
        if entry.get("status") == "justified":
            lines.append(f"- `{entry.get('callback_key')}`: {entry.get('reason') or entry.get('trigger_hint')}")
    return "\n".join(lines) + "\n"


def write_reports(
    entries: list[CallbackEntry],
    usage: dict[str, Counter[str]],
    coverage: list[dict[str, str]],
    categories: list[dict[str, str]],
    analysis: Path,
    evidence: dict,
) -> None:
    analysis.mkdir(parents=True, exist_ok=True)
    (analysis / "lua_callback_contexts.md").write_text(PROVENANCE + render_contexts(entries, usage, evidence), encoding="utf-8")
    (analysis / "callback_debug_cases.md").write_text(PROVENANCE + render_debug_cases(entries, usage, evidence), encoding="utf-8")
    (analysis / "callback_debug_coverage.md").write_text(PROVENANCE + render_coverage(coverage, categories, evidence), encoding="utf-8")
    (analysis / "callback_debug_manual_test_steps.md").write_text(
        PROVENANCE + render_manual_steps(coverage, categories),
        encoding="utf-8",
    )


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Catalog Lua callback signatures and usage evidence.")
    parser.add_argument("--analysis", type=Path, default=ANALYSIS, help="analysis output directory")
    return parser


def main() -> int:
    args = build_parser().parse_args()
    analysis = args.analysis if args.analysis.is_absolute() else ROOT / args.analysis
    entries = parse_stub_callbacks()
    usage = analyze_lua_usage()
    coverage, categories = parse_debug_mod_matrix()
    evidence = load_runtime_evidence()
    write_reports(entries, usage, coverage, categories, analysis, evidence)
    print(
        "Cataloged Lua callbacks: "
        f"stub_entries={len(entries)}, "
        f"lua_sources={len(lua_sources())}, "
        f"debug_cases={len(coverage)}, "
        f"debug_categories={len(categories)}."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
