from __future__ import annotations

import argparse
import json
import re
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
ANALYSIS = ROOT / "analysis"
PROVENANCE = """<!--
Generated by: tools/validate_debug_mod_real.py
Inputs:
- examples/callback_debug_mod_real/
Regenerate:
python tools/validate_debug_mod_real.py --root examples/callback_debug_mod_real
Do not edit manually unless explicitly noted.
-->

"""

DANGEROUS_CALL_PATTERNS = [
    r"\bSaveAllChanges\s*\(",
    r"\bResetAllData\s*\(",
    r"\bAddGlobalFlag\s*\(",
    r"\bForceTakeMoney\s*\(",
    r"\bOpenBrowser\s*\(",
    r"\bChangeWebsite\s*\(",
    r"\bio\.popen\s*\(",
]

REQUIRED_FALSE_FLAGS = [
    "ENABLE_DEBUG_ITEMS",
    "ENABLE_CALLBACK_PROBE",
    "DEBUG_ADD_TO_SHOP",
    "DEBUG_ENABLE_UI_CALLBACK_CASES",
    "DEBUG_ENABLE_STORY_CONDITION_CASES",
    "DEBUG_ENABLE_COROUTINE_CASES",
    "DEBUG_ENABLE_TEXTURE_CALLBACK_CASES",
]

PACKED_TEXTURE_RE = re.compile(r"GetPackedTexture\s*\(\s*CurrentModGuid\s*,\s*([^)]+)\)")
SPRITE_REFERENCE_RE = re.compile(r"GetSpriteReference\s*\(\s*CurrentModGuid\s*,\s*([^,]+)\s*,")
STRING_CONSTANT_RE = re.compile(r"\blocal\s+([A-Za-z_][A-Za-z0-9_]*)\s*=\s*([\"'])(.*?)\2")
LUA_STRING_FIELD_RE = re.compile(r"([A-Za-z_][A-Za-z0-9_]*)\s*=\s*([\"'])(.*?)\2", re.S)
LUA_BOOL_FIELD_RE = re.compile(r"([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(true|false)\b")

EXPECTED_ITEM_CATEGORIES = [
    "Clothing",
    "Food",
    "FoodCookedDish",
    "Usable",
    "Package",
    "Room",
    "Modules",
    "Fish",
    "CookingIngredient",
    "FishingTrash",
    "Meds",
    "Soap",
    "AnonEquip",
    "Other",
]

CRITICAL_CALLBACK_KEYS = [
    "ItemPrefab.OnUse",
    "ItemPrefab.OnUnpack",
    "ItemPrefab.SpecialEffectAction",
    "ItemPrefab.SetRandomItemPostProcessing",
    "EdibleItemPrefabData.CreateInstance",
    "EdibleItemPrefabData.CreateInstanceDish",
    "ModUtilities.AddSingleBuyItemToShop.availabilityFunc",
    "ModUtilities.AddGenericItemToShop.availabilityFunc",
    "ItemScopeConditionCustom.CreateInstance",
    "TextureOverriderManager.GetSpecialEffectsAction",
    "ItemPrefab.SetCustomShader",
    "StoryCondition.Delegate",
    "StoryCondition.Lua",
    "ModUtilities.StartCoroutine",
    "UiOverlay.*",
    "ItemManager.*events",
]


def rel(path: Path) -> str:
    try:
        return path.relative_to(ROOT).as_posix()
    except ValueError:
        return path.as_posix()


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8", errors="replace")


def load_json(path: Path) -> Any:
    with path.open("r", encoding="utf-8") as handle:
        return json.load(handle)


def validate_mod_json(root: Path, errors: list[str], warnings: list[str]) -> list[str]:
    mod_json = root / "mod.json"
    if not mod_json.exists():
        errors.append("Missing mod.json")
        return []

    try:
        data = load_json(mod_json)
    except Exception as exc:  # noqa: BLE001
        errors.append(f"Invalid mod.json: {exc}")
        return []

    lua_files = data.get("OnGameStart", {}).get("luaFiles", [])
    if not isinstance(lua_files, list) or not lua_files:
        errors.append("mod.json OnGameStart.luaFiles must be a non-empty list")
        return []

    result: list[str] = []
    for item in lua_files:
        if not isinstance(item, str):
            errors.append(f"luaFiles entry is not a string: {item!r}")
            continue
        if Path(item).is_absolute() or ".." in Path(item).parts:
            errors.append(f"luaFiles entry must be local: {item}")
            continue
        target = root / item
        if not target.exists():
            errors.append(f"luaFiles entry missing: {item}")
        else:
            result.append(item)

    guid = data.get("doNotChangeVariablesBelowThis", {}).get("guid", {}).get("serializedGuid")
    if not isinstance(guid, str) or not re.match(
        r"^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$",
        guid or "",
    ):
        warnings.append("mod.json GUID is missing or not UUID-shaped")

    return result


def validate_flags(script_text: str, errors: list[str]) -> None:
    for flag in REQUIRED_FALSE_FLAGS:
        match = re.search(rf"\blocal\s+{re.escape(flag)}\s*=\s*(true|false)\b", script_text)
        if not match:
            errors.append(f"Missing local flag: {flag}")
        elif match.group(1) != "false":
            errors.append(f"Flag must default to false: {flag}")


def validate_dangerous_calls(path: Path, text: str, errors: list[str]) -> None:
    for pattern in DANGEROUS_CALL_PATTERNS:
        for match in re.finditer(pattern, text):
            line = text.count("\n", 0, match.start()) + 1
            errors.append(f"Dangerous call pattern in {rel(path)}:{line}: {pattern}")


def validate_packed_texture_json(path: Path, errors: list[str]) -> None:
    try:
        data = load_json(path)
    except Exception as exc:  # noqa: BLE001
        errors.append(f"Invalid packed texture JSON {rel(path)}: {exc}")
        return

    textures = data.get("PackedTextures")
    if not isinstance(textures, list) or not textures:
        errors.append(f"PackedTextures must be a non-empty list: {rel(path)}")
        return

    for texture_index, texture in enumerate(textures):
        if not isinstance(texture, dict):
            errors.append(f"PackedTextures[{texture_index}] is not an object: {rel(path)}")
            continue

        texture_name = texture.get("TextureName")
        if not isinstance(texture_name, str) or not texture_name:
            errors.append(f"PackedTextures[{texture_index}].TextureName missing: {rel(path)}")
        else:
            png_path = path.parent / texture_name
            if not png_path.exists():
                errors.append(f"TextureName target missing: {rel(path)} -> {texture_name}")

        targets = texture.get("Targets")
        if not isinstance(targets, list) or not targets:
            errors.append(f"PackedTextures[{texture_index}].Targets must be non-empty: {rel(path)}")

        drawables = texture.get("PackedDrawables")
        if not isinstance(drawables, list) or not drawables:
            errors.append(f"PackedTextures[{texture_index}].PackedDrawables must be non-empty: {rel(path)}")


def resolve_mod_path(root: Path, mod_path: str) -> Path:
    normalized = mod_path[1:] if mod_path.startswith("/") else mod_path
    return root / normalized


def extract_string_constants(script_text: str) -> dict[str, str]:
    constants: dict[str, str] = {}
    for match in STRING_CONSTANT_RE.finditer(script_text):
        constants[match.group(1)] = match.group(3)
    return constants


def resolve_texture_arg(raw_arg: str, constants: dict[str, str], errors: list[str]) -> str | None:
    raw_arg = raw_arg.strip()
    literal = re.match(r"^([\"'])(.*?)\1$", raw_arg)
    if literal:
        return literal.group(2)
    if re.match(r"^[A-Za-z_][A-Za-z0-9_]*$", raw_arg):
        if raw_arg in constants:
            return constants[raw_arg]
        errors.append(f"GetPackedTexture path variable is not a local string constant: {raw_arg}")
        return None
    errors.append(f"GetPackedTexture path expression is not statically validated: {raw_arg}")
    return None


def validate_texture_paths(root: Path, script_text: str, errors: list[str]) -> list[str]:
    constants = extract_string_constants(script_text)
    paths = []
    for regex in [PACKED_TEXTURE_RE, SPRITE_REFERENCE_RE]:
        for match in regex.finditer(script_text):
            mod_path = resolve_texture_arg(match.group(1), constants, errors)
            if mod_path is None:
                continue
            paths.append(mod_path)
            if not mod_path.startswith("/"):
                errors.append(f"Asset path must be absolute inside mod: {mod_path}")
                continue
            target = resolve_mod_path(root, mod_path)
            if not target.exists():
                errors.append(f"Asset path missing: {mod_path}")
                continue
            if target.suffix.lower() == ".json":
                validate_packed_texture_json(target, errors)
    return sorted(set(paths))


def extract_lua_table_block(text: str, local_name: str) -> str:
    match = re.search(rf"\blocal\s+{re.escape(local_name)}\s*=\s*\{{", text)
    if not match:
        return ""
    start = text.find("{", match.start())
    depth = 0
    in_string: str | None = None
    escaped = False
    for index in range(start, len(text)):
        char = text[index]
        if in_string:
            if escaped:
                escaped = False
            elif char == "\\":
                escaped = True
            elif char == in_string:
                in_string = None
            continue
        if char in {"'", '"'}:
            in_string = char
            continue
        if char == "{":
            depth += 1
        elif char == "}":
            depth -= 1
            if depth == 0:
                return text[start + 1:index]
    return text[start + 1:]


def split_top_level_table_entries(block: str) -> list[str]:
    entries: list[str] = []
    current: list[str] = []
    depth = 0
    in_string: str | None = None
    escaped = False
    entry_start_depth = 0
    for char in block:
        if in_string:
            current.append(char)
            if escaped:
                escaped = False
            elif char == "\\":
                escaped = True
            elif char == in_string:
                in_string = None
            continue
        if char in {"'", '"'}:
            in_string = char
            current.append(char)
            continue
        if char == "{":
            if depth == 0:
                current = []
                entry_start_depth = 1
            else:
                current.append(char)
            depth += 1
            continue
        if char == "}":
            depth -= 1
            if depth == 0 and entry_start_depth:
                entries.append("".join(current))
                current = []
                entry_start_depth = 0
            else:
                current.append(char)
            continue
        if depth > 0:
            current.append(char)
    return entries


def parse_lua_key_values(entry: str) -> dict[str, str]:
    fields: dict[str, str] = {}
    for match in LUA_STRING_FIELD_RE.finditer(entry):
        fields[match.group(1)] = match.group(3)
    for match in LUA_BOOL_FIELD_RE.finditer(entry):
        fields.setdefault(match.group(1), match.group(2))
    return fields


def parse_debug_matrix(script_text: str) -> tuple[list[dict[str, str]], list[dict[str, str]]]:
    coverage: list[dict[str, str]] = []
    categories: list[dict[str, str]] = []
    for table_name, target in [
        ("DEBUG_CALLBACK_COVERAGE", coverage),
        ("DEBUG_ITEM_CATEGORIES", categories),
    ]:
        block = extract_lua_table_block(script_text, table_name)
        for entry in split_top_level_table_entries(block):
            fields = parse_lua_key_values(entry)
            if table_name == "DEBUG_CALLBACK_COVERAGE" and {"callback_key", "case_id", "status"} <= fields.keys():
                target.append(fields)
            elif table_name == "DEBUG_ITEM_CATEGORIES" and {"category_name", "id"} <= fields.keys():
                target.append(fields)
    return coverage, categories


def validate_debug_matrix(script_text: str, errors: list[str]) -> tuple[list[dict[str, str]], list[dict[str, str]]]:
    coverage, categories = parse_debug_matrix(script_text)
    category_names = {entry.get("category_name") for entry in categories}
    for category in EXPECTED_ITEM_CATEGORIES:
        if category not in category_names:
            errors.append(f"Missing debug item category case: {category}")

    coverage_by_key = {entry.get("callback_key"): entry for entry in coverage}
    for key in CRITICAL_CALLBACK_KEYS:
        entry = coverage_by_key.get(key)
        if not entry:
            errors.append(f"Missing critical callback coverage entry: {key}")
            continue
        status = entry.get("status")
        if status not in {"covered", "justified", "conditional"}:
            errors.append(f"Invalid coverage status for {key}: {status}")
        if status in {"justified", "conditional"} and not (entry.get("reason") or entry.get("trigger_hint")):
            errors.append(f"{status} callback coverage needs reason or trigger_hint: {key}")
    return coverage, categories


def render_report(
    root: Path,
    lua_files: list[str],
    texture_paths: list[str],
    coverage: list[dict[str, str]],
    categories: list[dict[str, str]],
    errors: list[str],
    warnings: list[str],
) -> str:
    lines = [
        "# Debug mod real asset requirements",
        "",
        f"Root: `{rel(root)}`",
        "",
        "## Lua files",
        "",
    ]
    if lua_files:
        lines.extend(f"- `{item}`" for item in lua_files)
    else:
        lines.append("- None")

    lines.extend(["", "## Packed texture paths", ""])
    if texture_paths:
        for item in texture_paths:
            lines.append(f"- `{item}`")
    else:
        lines.append("- None")

    lines.extend(["", "## Debug item categories", ""])
    if categories:
        for item in categories:
            lines.append(f"- `{item.get('category_name')}` -> `{item.get('id')}`")
    else:
        lines.append("- None")

    lines.extend(["", "## Critical callback coverage", ""])
    if coverage:
        for item in coverage:
            lines.append(
                f"- `{item.get('callback_key')}` -> `{item.get('case_id')}` ({item.get('status')})"
            )
    else:
        lines.append("- None")

    lines.extend(["", "## Validation", ""])
    lines.append(f"- Errors: {len(errors)}")
    lines.append(f"- Warnings: {len(warnings)}")
    if errors:
        lines.extend(["", "Errors:"])
        lines.extend(f"- {item}" for item in errors)
    if warnings:
        lines.extend(["", "Warnings:"])
        lines.extend(f"- {item}" for item in warnings)
    return PROVENANCE + "\n".join(lines) + "\n"


def validate(root: Path) -> tuple[list[str], list[str], list[str], list[str]]:
    errors: list[str] = []
    warnings: list[str] = []
    lua_files = validate_mod_json(root, errors, warnings)

    all_text = ""
    script_text = ""
    for lua_file in lua_files:
        path = root / lua_file
        text = read_text(path)
        all_text += "\n" + text
        validate_dangerous_calls(path, text, errors)
        if lua_file == "script.lua":
            script_text = text

    if not script_text:
        errors.append("Missing script.lua in luaFiles")
    else:
        validate_flags(script_text, errors)

    texture_paths = validate_texture_paths(root, script_text, errors) if script_text else []
    coverage: list[dict[str, str]] = []
    categories: list[dict[str, str]] = []
    if script_text:
        coverage, categories = validate_debug_matrix(script_text, errors)

    helper = root / "mdrg_callback_context_probe.lua"
    if helper.exists():
        helper_text = read_text(helper)
        if "local ENABLE_CALLBACK_PROBE = false" not in helper_text:
            errors.append("Callback helper must default ENABLE_CALLBACK_PROBE to false")
        for marker in ["debug_case_id", "callback_kind", "expected_signature", "source_stub", "trigger_hint"]:
            if marker not in helper_text:
                errors.append(f"Callback helper missing metadata marker: {marker}")
    else:
        errors.append("Missing mdrg_callback_context_probe.lua")

    if "mod/realmod" in all_text.replace("\\", "/"):
        warnings.append("Debug mod script references mod/realmod textually")

    return errors, warnings, lua_files, texture_paths, coverage, categories


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Validate the opt-in callback debug mod.")
    parser.add_argument("--root", type=Path, default=ROOT / "examples" / "callback_debug_mod_real")
    parser.add_argument("--no-report", action="store_true", help="Do not write analysis report")
    return parser


def main() -> int:
    args = build_parser().parse_args()
    root = args.root if args.root.is_absolute() else ROOT / args.root
    errors, warnings, lua_files, texture_paths, coverage, categories = validate(root)

    if not args.no_report:
        ANALYSIS.mkdir(parents=True, exist_ok=True)
        (ANALYSIS / "debug_mod_real_asset_requirements.md").write_text(
            render_report(root, lua_files, texture_paths, coverage, categories, errors, warnings),
            encoding="utf-8",
        )

    print(
        "Validated callback debug mod: "
        f"lua_files={len(lua_files)}, "
        f"packed_texture_paths={len(texture_paths)}, "
        f"coverage_entries={len(coverage)}, "
        f"category_cases={len(categories)}, "
        f"errors={len(errors)}, "
        f"warnings={len(warnings)}."
    )
    if errors:
        for item in errors:
            print(f"ERROR: {item}")
        return 1
    for item in warnings:
        print(f"WARNING: {item}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
