from __future__ import annotations

import argparse
import json
import re
from collections import Counter, defaultdict
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_MOD_ROOT = ROOT / "mod" / "realmod"
DEFAULT_ANALYSIS = ROOT / "analysis"
PROVENANCE = """<!--
Generated by: tools/validate_realmod_assets.py
Inputs:
- mod/realmod or supplied --root
Regenerate:
python tools/validate_realmod_assets.py --root mod/realmod
Do not edit manually unless explicitly noted.
-->

"""


PACKED_TEXTURES_SCHEMA: dict[str, Any] = {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "title": "MDRG PackedTextures asset",
    "type": "object",
    "required": ["PackedTextures"],
    "additionalProperties": True,
    "properties": {
        "PackedTextures": {
            "type": "array",
            "minItems": 1,
            "items": {
                "type": "object",
                "required": [
                    "TextureName",
                    "Layer",
                    "PackedDrawables",
                    "Targets",
                    "DontIncludeVanillaLayers",
                ],
                "additionalProperties": True,
                "properties": {
                    "TextureName": {"type": "string", "minLength": 1},
                    "Layer": {"type": "integer"},
                    "PackedDrawables": {
                        "type": "array",
                        "minItems": 1,
                        "items": {
                            "type": "object",
                            "required": [
                                "Name",
                                "RectInt",
                                "ColorIndex",
                                "DrawableType",
                                "BypassColorScaler",
                            ],
                            "additionalProperties": True,
                            "properties": {
                                "Name": {"type": "string"},
                                "RectInt": {
                                    "type": "object",
                                    "required": ["x", "y", "width", "height"],
                                    "properties": {
                                        "x": {"type": "integer"},
                                        "y": {"type": "integer"},
                                        "width": {"type": "integer", "exclusiveMinimum": 0},
                                        "height": {"type": "integer", "exclusiveMinimum": 0},
                                    },
                                },
                                "ColorIndex": {"type": "integer"},
                                "DrawableType": {"type": "integer"},
                                "BypassColorScaler": {"type": "boolean"},
                            },
                        },
                    },
                    "Targets": {"type": "array", "minItems": 1, "items": {"type": "string"}},
                    "DontIncludeVanillaLayers": {"type": "boolean"},
                },
            },
        }
    },
}


@dataclass
class AssetValidation:
    mod_root: Path
    analysis_dir: Path
    mode: str = "strict"
    top_files: list[str] = field(default_factory=list)
    folders: list[str] = field(default_factory=list)
    all_jsons: list[Path] = field(default_factory=list)
    asset_jsons: list[Path] = field(default_factory=list)
    all_pngs: list[Path] = field(default_factory=list)
    referenced_pngs: set[Path] = field(default_factory=set)
    script_texture_paths: list[str] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)
    compatibility_warnings: list[str] = field(default_factory=list)
    errors: list[str] = field(default_factory=list)
    layers: Counter[int] = field(default_factory=Counter)
    targets: Counter[str] = field(default_factory=Counter)
    drawable_types: Counter[int] = field(default_factory=Counter)
    color_indexes: Counter[int] = field(default_factory=Counter)
    packed_counts: Counter[int] = field(default_factory=Counter)
    categories: Counter[str] = field(default_factory=Counter)
    shops: Counter[str] = field(default_factory=Counter)
    slots: Counter[str] = field(default_factory=Counter)
    subcategories: Counter[str] = field(default_factory=Counter)
    item_counts: Counter[str] = field(default_factory=Counter)
    texture_jsons_used: set[Path] = field(default_factory=set)

    def rel(self, path: Path) -> str:
        return path.relative_to(self.mod_root).as_posix()


def load_json(path: Path, result: AssetValidation) -> Any | None:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception as exc:  # noqa: BLE001 - report-only tool
        result.errors.append(f"{result.rel(path)}: invalid JSON: {exc}")
        return None


def expect_type(value: Any, typ: type, label: str, result: AssetValidation) -> bool:
    if isinstance(value, typ) and not (typ is int and isinstance(value, bool)):
        return True
    result.errors.append(f"{label}: expected {typ.__name__}, got {type(value).__name__}")
    return False


def validate_rect(rect: Any, label: str, result: AssetValidation) -> None:
    if not expect_type(rect, dict, label, result):
        return
    for key in ["x", "y", "width", "height"]:
        if key not in rect:
            result.errors.append(f"{label}.{key}: missing")
        elif expect_type(rect[key], int, f"{label}.{key}", result) and key in {"width", "height"} and rect[key] <= 0:
            result.errors.append(f"{label}.{key}: must be > 0")


def report_missing(label: str, key: str, result: AssetValidation, compat_warning: bool = False) -> None:
    message = f"{label}.{key}: missing"
    if result.mode == "compat" and compat_warning:
        result.compatibility_warnings.append(message)
    else:
        result.errors.append(message)


def expect_type_compat(
    value: Any,
    typ: type,
    label: str,
    result: AssetValidation,
    compat_warning: bool = False,
) -> bool:
    if isinstance(value, typ) and not (typ is int and isinstance(value, bool)):
        return True
    message = f"{label}: expected {typ.__name__}, got {type(value).__name__}"
    if result.mode == "compat" and compat_warning:
        result.compatibility_warnings.append(message)
    else:
        result.errors.append(message)
    return False


def validate_asset_json(path: Path, data: Any, result: AssetValidation) -> None:
    if not expect_type(data, dict, result.rel(path), result):
        return
    packed = data.get("PackedTextures")
    if not expect_type(packed, list, f"{result.rel(path)}.PackedTextures", result):
        return
    if not packed:
        result.errors.append(f"{result.rel(path)}.PackedTextures: empty")
        return

    result.packed_counts[len(packed)] += 1
    for index, texture in enumerate(packed):
        label = f"{result.rel(path)}.PackedTextures[{index}]"
        if not expect_type(texture, dict, label, result):
            continue
        for key in ["Layer", "PackedDrawables"]:
            if key not in texture:
                result.errors.append(f"{label}.{key}: missing")
        for key in ["Targets", "DontIncludeVanillaLayers"]:
            if key not in texture:
                report_missing(label, key, result, compat_warning=True)

        texture_name = texture.get("TextureName")
        if texture_name is None and result.mode == "compat" and "Texture" in texture:
            texture_name = texture.get("Texture")
            result.compatibility_warnings.append(f"{label}.Texture: legacy texture field used as TextureName")
        if expect_type(texture_name, str, f"{label}.TextureName", result):
            png_path = path.parent / texture_name
            if png_path.exists():
                result.referenced_pngs.add(png_path.resolve())
            else:
                result.errors.append(f"{label}.TextureName: PNG missing in same folder: {texture_name}")

        layer = texture.get("Layer")
        if expect_type(layer, int, f"{label}.Layer", result):
            result.layers[layer] += 1

        targets = texture.get("Targets")
        if targets is not None and expect_type_compat(targets, list, f"{label}.Targets", result, compat_warning=True):
            if not targets:
                if result.mode == "compat":
                    result.compatibility_warnings.append(f"{label}.Targets: empty")
                else:
                    result.errors.append(f"{label}.Targets: empty")
            for target in targets:
                if expect_type(target, str, f"{label}.Targets[]", result):
                    result.targets[target] += 1

        if "DontIncludeVanillaLayers" in texture:
            expect_type_compat(
                texture.get("DontIncludeVanillaLayers"),
                bool,
                f"{label}.DontIncludeVanillaLayers",
                result,
                compat_warning=True,
            )

        drawables = texture.get("PackedDrawables")
        if expect_type(drawables, list, f"{label}.PackedDrawables", result):
            if not drawables:
                result.errors.append(f"{label}.PackedDrawables: empty")
            for drawable_index, drawable in enumerate(drawables):
                drawable_label = f"{label}.PackedDrawables[{drawable_index}]"
                if not expect_type(drawable, dict, drawable_label, result):
                    continue
                for key in ["Name", "RectInt", "ColorIndex"]:
                    if key not in drawable:
                        result.errors.append(f"{drawable_label}.{key}: missing")
                for key in ["DrawableType", "BypassColorScaler"]:
                    if key not in drawable:
                        report_missing(drawable_label, key, result, compat_warning=True)
                expect_type(drawable.get("Name"), str, f"{drawable_label}.Name", result)
                validate_rect(drawable.get("RectInt"), f"{drawable_label}.RectInt", result)
                color_index = drawable.get("ColorIndex")
                if expect_type(color_index, int, f"{drawable_label}.ColorIndex", result):
                    result.color_indexes[color_index] += 1
                drawable_type = drawable.get("DrawableType")
                if drawable_type is not None and expect_type_compat(
                    drawable_type,
                    int,
                    f"{drawable_label}.DrawableType",
                    result,
                    compat_warning=True,
                ):
                    result.drawable_types[drawable_type] += 1
                if "BypassColorScaler" in drawable:
                    expect_type_compat(
                        drawable.get("BypassColorScaler"),
                        bool,
                        f"{drawable_label}.BypassColorScaler",
                        result,
                        compat_warning=True,
                    )


def extract_script_patterns(result: AssetValidation) -> None:
    script = result.mod_root / "script.lua"
    if not script.exists():
        result.errors.append("script.lua missing")
        return
    text = script.read_text(encoding="utf-8", errors="replace")
    result.script_texture_paths = re.findall(r"GetPackedTexture\s*\([^)]*?['\"](/[^'\"]+\.json)['\"]", text, re.S)
    for path_text in result.script_texture_paths:
        if not path_text.startswith("/"):
            result.errors.append(f"GetPackedTexture path does not start with '/': {path_text}")
            continue
        asset = result.mod_root / path_text.lstrip("/")
        if asset.exists():
            result.texture_jsons_used.add(asset.resolve())
        else:
            result.errors.append(f"GetPackedTexture asset path missing: {path_text}")

    result.item_counts["CreateItemPrefab"] = len(re.findall(r"\bCreateItemPrefab\s*\(", text))
    result.item_counts["CreateNewItemAutoAssignId"] = len(re.findall(r"\bCreateNewItemAutoAssignId\s*\(", text))
    result.item_counts["AddTexture"] = len(re.findall(r"\.AddTexture\s*\(", text))
    result.item_counts["EdibleData"] = len(re.findall(r"\.EdibleData\s*=", text))
    result.item_counts["FishData"] = len(re.findall(r"\.FishData\s*=", text))
    result.item_counts["PackageData"] = len(re.findall(r"\.PackageData\s*=", text))
    result.item_counts["SpecialEffectAction"] = len(re.findall(r"\.SpecialEffectAction\s*=", text))
    result.item_counts["OnUse"] = len(re.findall(r"\.OnUse\s*=", text))

    for category in re.findall(r"\.Category\s*=\s*ItemCategory\.([A-Za-z0-9_]+)", text):
        result.categories[category] += 1
    for shop in re.findall(r"AddSingleBuyItemToShop\s*\(\s*['\"]([^'\"]+)['\"]", text):
        result.shops[shop] += 1
    for slot in re.findall(r"SlotEquipData\.CreateInstance\s*\(\s*['\"]([^'\"]+)['\"]", text):
        result.slots[slot] += 1
    for slot in re.findall(r"\.TargetSlotString\s*=\s*['\"]([^'\"]+)['\"]", text):
        result.slots[slot] += 1
    for subcategory in re.findall(r"\.SubCategory\s*=\s*ItemSubCategory\.([A-Za-z0-9_]+)", text):
        result.subcategories[subcategory] += 1


def analyze_mod(root: Path, analysis_dir: Path, mode: str = "strict") -> AssetValidation:
    result = AssetValidation(root, analysis_dir, mode=mode)
    result.top_files = sorted(path.name for path in root.iterdir() if path.is_file())
    result.folders = sorted(path.name for path in root.iterdir() if path.is_dir())
    result.all_jsons = sorted(root.rglob("*.json"))
    result.all_pngs = sorted(root.rglob("*.png"))

    for json_path in result.all_jsons:
        data = load_json(json_path, result)
        if isinstance(data, dict) and "PackedTextures" in data:
            result.asset_jsons.append(json_path)
            validate_asset_json(json_path, data, result)

    extract_script_patterns(result)

    referenced = result.referenced_pngs
    for png in result.all_pngs:
        if png.resolve() not in referenced:
            result.warnings.append(f"orphan PNG not referenced by asset JSON: {result.rel(png)}")

    for asset_json in result.asset_jsons:
        if asset_json.resolve() not in result.texture_jsons_used:
            result.warnings.append(f"asset JSON not referenced by script.lua: {result.rel(asset_json)}")

    return result


def md_counter(counter: Counter[Any], limit: int = 80) -> list[str]:
    if not counter:
        return ["- None"]
    return [f"- `{key}`: {count}" for key, count in counter.most_common(limit)]


def write_reports(result: AssetValidation) -> None:
    result.analysis_dir.mkdir(parents=True, exist_ok=True)
    (result.analysis_dir / "packed_textures.schema.json").write_text(
        json.dumps(PACKED_TEXTURES_SCHEMA, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )

    structure_lines = [
        "# Realmod structure",
        "",
        f"- Root: `{result.mod_root.as_posix()}`",
        f"- Validation mode: {result.mode}",
        f"- Top-level files: {len(result.top_files)}",
        f"- Asset folders: {len(result.folders)}",
        f"- JSON files total: {len(result.all_jsons)}",
        f"- PackedTextures JSON files: {len(result.asset_jsons)}",
        f"- PNG files: {len(result.all_pngs)}",
        "",
        "## Top-level files",
        "",
        *[f"- `{name}`" for name in result.top_files],
        "",
        "## OnGameStart",
        "",
    ]
    mod_json = load_json(result.mod_root / "mod.json", result)
    if isinstance(mod_json, dict):
        lua_files = mod_json.get("OnGameStart", {}).get("luaFiles", [])
        structure_lines.extend(f"- `{name}`" for name in lua_files)
    else:
        structure_lines.append("- mod.json could not be parsed")
    structure_lines.extend(
        [
            "",
            "## Asset folders",
            "",
            *[f"- `{name}`" for name in result.folders],
            "",
            "## Validation summary",
            "",
            f"- Errors: {len(result.errors)}",
            f"- Warnings: {len(result.warnings)}",
            f"- Compatibility warnings: {len(result.compatibility_warnings)}",
        ]
    )
    (result.analysis_dir / "realmod_structure.md").write_text(PROVENANCE + "\n".join(structure_lines) + "\n", encoding="utf-8")

    schema_lines = [
        "# Realmod asset schema",
        "",
        "Packed texture assets are JSON files with a root `PackedTextures` array. `mod.json` is not a packed texture asset.",
        "",
        f"- Validation mode: {result.mode}",
        "",
        "## Observed values",
        "",
        "Layers:",
        *md_counter(result.layers),
        "",
        "Targets:",
        *md_counter(result.targets),
        "",
        "DrawableType:",
        *md_counter(result.drawable_types),
        "",
        "ColorIndex:",
        *md_counter(result.color_indexes),
        "",
        "PackedTextures entries per JSON:",
        *md_counter(result.packed_counts),
        "",
        "## Lua asset loading pattern",
        "",
        "Lua references the JSON, not the PNG directly:",
        "",
        "```lua",
        'local packed = ModUtilities.GetPackedTexture(CurrentModGuid, "/Folder/file.json")',
        "itemprefab.AddTexture(packed)",
        "```",
        "",
        "The JSON `TextureName` points to a PNG in the same folder.",
    ]
    (result.analysis_dir / "realmod_asset_schema.md").write_text(PROVENANCE + "\n".join(schema_lines) + "\n", encoding="utf-8")

    pattern_lines = [
        "# Realmod item patterns",
        "",
        "## Counts",
        "",
        *md_counter(result.item_counts),
        "",
        "## Categories",
        "",
        *md_counter(result.categories),
        "",
        "## Shops",
        "",
        *md_counter(result.shops),
        "",
        "## Slots",
        "",
        *md_counter(result.slots, 120),
        "",
        "## Subcategories",
        "",
        *md_counter(result.subcategories, 120),
        "",
        "## Practical patterns",
        "",
        "- Items are created with `ModUtilities.CreateItemPrefab()`.",
        "- Assets are loaded with `ModUtilities.GetPackedTexture(CurrentModGuid, \"/...json\")`.",
        "- Packed textures are attached with `itemprefab.AddTexture(packed)`.",
        "- Items are registered with `ModUtilities.CreateNewItemAutoAssignId(CurrentModGuid, itemprefab)`.",
        "- Shops are populated with `ModUtilities.AddSingleBuyItemToShop(shopId, itemgameid)`.",
    ]
    (result.analysis_dir / "realmod_item_patterns.md").write_text(PROVENANCE + "\n".join(pattern_lines) + "\n", encoding="utf-8")

    validation_lines = [
        "# Realmod asset validation",
        "",
        f"- Validation mode: {result.mode}",
        f"- PackedTextures JSON files: {len(result.asset_jsons)}",
        f"- Script GetPackedTexture paths: {len(result.script_texture_paths)}",
        f"- Referenced PNGs: {len(result.referenced_pngs)}",
        f"- PNG files: {len(result.all_pngs)}",
        f"- Errors: {len(result.errors)}",
        f"- Warnings: {len(result.warnings)}",
        f"- Compatibility warnings: {len(result.compatibility_warnings)}",
        "",
        "## Errors",
        "",
        *(f"- {error}" for error in result.errors[:500]),
        "",
        "## Warnings",
        "",
        *(f"- {warning}" for warning in result.warnings[:500]),
        "",
        "## Compatibility warnings",
        "",
        *(f"- {warning}" for warning in result.compatibility_warnings[:500]),
    ]
    if not result.errors:
        validation_lines[validation_lines.index("## Errors") + 2:validation_lines.index("## Warnings") - 1] = ["- None"]
    if not result.warnings:
        warnings_index = validation_lines.index("## Warnings")
        compatibility_index = validation_lines.index("## Compatibility warnings")
        validation_lines[warnings_index + 2:compatibility_index - 1] = ["- None"]
    if not result.compatibility_warnings:
        validation_lines.append("- None")
    (result.analysis_dir / "realmod_asset_validation.md").write_text(
        PROVENANCE + "\n".join(validation_lines) + "\n",
        encoding="utf-8",
    )


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Validate and document MDRG realmod assets.")
    parser.add_argument("--root", type=Path, default=DEFAULT_MOD_ROOT, help="mod root directory")
    parser.add_argument("--analysis", type=Path, default=DEFAULT_ANALYSIS, help="analysis output directory")
    parser.add_argument("--mode", choices=["strict", "compat"], default="strict", help="validation mode")
    parser.add_argument("--compat", action="store_true", help="shortcut for --mode compat")
    return parser


def main() -> int:
    args = build_parser().parse_args()
    mod_root = args.root if args.root.is_absolute() else ROOT / args.root
    analysis_dir = args.analysis if args.analysis.is_absolute() else ROOT / args.analysis
    mode = "compat" if args.compat else args.mode
    result = analyze_mod(mod_root, analysis_dir, mode)
    write_reports(result)
    print(
        "Validated realmod assets: "
        f"mode={result.mode}, "
        f"asset_jsons={len(result.asset_jsons)}, "
        f"pngs={len(result.all_pngs)}, "
        f"errors={len(result.errors)}, "
        f"warnings={len(result.warnings)}, "
        f"compatibility_warnings={len(result.compatibility_warnings)}."
    )
    return 1 if result.errors else 0


if __name__ == "__main__":
    raise SystemExit(main())
